Support Kotlin inline functions: try to access SDE from class files on disk
JetBrains/async-profiler pull request #3
Opened 2022-08-08 13:01 UTC by zuevmaxim

In ClassFileLoad hook the `protection_domain` parameter is used to locate the class file on disk, where it is possible to extract SDE.

2022-08-10 14:17 UTC, nikita-nazarov requested changes

2022-08-10 14:17 UTC, nikita-nazarov commented on src/debugInfoAccess.cpp
> +std::string urlDecode(const char* src) {
This looks like a hack to the utf encoding problem. Discussed in DM.

2022-08-10 14:17 UTC, nikita-nazarov commented on src/fileAccess.cpp
> +    FileResource(std::ifstream& bin_file) : Resource(), _buffer(std::istreambuf_iterator<char>(bin_file), std::istreambuf_iterator<char>()) {}
Maybe it would be better to split this line?

2022-08-10 14:17 UTC, nikita-nazarov commented on src/fileAccess.cpp
> +bool endsWith(const std::string& fullString, const std::string& ending) {
This function can be static.

2022-08-10 14:17 UTC, nikita-nazarov commented on src/debugInfoAccess.cpp
> +    std::map<std::string, std::vector<std::string> > class_files;
`std::map<std::string, std::vector<std::string> > class_files(std::move(_class_files))` ?

2022-08-10 16:07 UTC, zuevmaxim commented on src/debugInfoAccess.cpp
> +    std::map<std::string, std::vector<std::string> > class_files;
Looks like `std::move` is unavailable until c++11: https://en.cppreference.com/w/cpp/utility/move

2022-08-12 13:28 UTC, zuevmaxim commented on src/debugInfoAccess.cpp
> +std::string urlDecode(const char* src) {
This method is replaced with java `URLDecoder#decode` call

2022-08-18 20:24 UTC, nikita-nazarov approved these changes

2022-08-19 08:46 UTC, closed without merging